### ISSUE TITLE
1.0.4.0 fails to build with GHC 8.8 and up

### ISSUE THREAD

**Issue by andreasabel** [achirkin/constraints-deriving#4]
```
constraints-deriving-1.0.4.0$ cabal build -w ghc-8.8.4
...
src/Data/Constraint/Deriving/CorePluginM.hs:283:5: error:
    • Illegal equational constraint SrcSpanLess a ~ ModuleName
      (Use GADTs or TypeFamilies to permit this)
    • When checking the inferred type
        lookupDep :: forall (f :: * -> *) a.
                     (MonadIO f, HasSrcSpan a, SrcSpanLess a ~ ModuleName) =>
                     HscEnv -> (Maybe FastString, a) -> f (Maybe Module)
      In an equation for ‘defCorePluginEnv’:
...
```

**Comment by andreasabel** [comment]
Fixed by revision 1: https://hackage.haskell.org/package/constraints-deriving-1.0.4.0/revisions/

Also for the other `1.0.x` versions.
